# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/elena/OneDrive/Desktop/facultate/an2/AC/newtry pipe/MIPS16_pipeline_v2/MIPS16_pipeline.cache/wt} [current_project]
set_property parent.project_path {C:/Users/elena/OneDrive/Desktop/facultate/an2/AC/newtry pipe/MIPS16_pipeline_v2/MIPS16_pipeline.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/elena/OneDrive/Desktop/facultate/an2/AC/newtry pipe/MIPS16_pipeline_v2/MIPS16_pipeline.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/elena/OneDrive/Desktop/facultate/an2/AC/newtry pipe/MIPS16_pipeline_v2/MIPS16_pipeline.srcs/sources_1/new/RF.vhd}
  {C:/Users/elena/OneDrive/Desktop/facultate/an2/AC/newtry pipe/MIPS16_pipeline_v2/MIPS16_pipeline.srcs/sources_1/new/HEX7TOSEG.vhd}
  {C:/Users/elena/OneDrive/Desktop/facultate/an2/AC/newtry pipe/MIPS16_pipeline_v2/MIPS16_pipeline.srcs/sources_1/new/MEM.vhd}
  {C:/Users/elena/OneDrive/Desktop/facultate/an2/AC/newtry pipe/MIPS16_pipeline_v2/MIPS16_pipeline.srcs/sources_1/new/EX.vhd}
  {C:/Users/elena/OneDrive/Desktop/facultate/an2/AC/newtry pipe/MIPS16_pipeline_v2/MIPS16_pipeline.srcs/sources_1/new/ID.vhd}
  {C:/Users/elena/OneDrive/Desktop/facultate/an2/AC/newtry pipe/MIPS16_pipeline_v2/MIPS16_pipeline.srcs/sources_1/new/IF.vhd}
  {C:/Users/elena/OneDrive/Desktop/facultate/an2/AC/newtry pipe/MIPS16_pipeline_v2/MIPS16_pipeline.srcs/sources_1/new/SSD.vhd}
  {C:/Users/elena/OneDrive/Desktop/facultate/an2/AC/newtry pipe/MIPS16_pipeline_v2/MIPS16_pipeline.srcs/sources_1/new/monoimpuls.vhd}
  {C:/Users/elena/OneDrive/Desktop/facultate/an2/AC/newtry pipe/MIPS16_pipeline_v2/MIPS16_pipeline.srcs/sources_1/new/UC.vhd}
  {C:/Users/elena/OneDrive/Desktop/facultate/an2/AC/newtry pipe/MIPS16_pipeline_v2/MIPS16_pipeline.srcs/sources_1/new/mips16_pipe.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/elena/OneDrive/Desktop/facultate/an2/AC/newtry pipe/MIPS16_pipeline_v2/MIPS16_pipeline.srcs/constrs_1/new/Basys3_constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/elena/OneDrive/Desktop/facultate/an2/AC/newtry pipe/MIPS16_pipeline_v2/MIPS16_pipeline.srcs/constrs_1/new/Basys3_constraints.xdc}}]


synth_design -top mips16_pipe -part xc7a35tcpg236-1


write_checkpoint -force -noxdef mips16_pipe.dcp

catch { report_utilization -file mips16_pipe_utilization_synth.rpt -pb mips16_pipe_utilization_synth.pb }
